
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Aug 20 2025 13:53:33 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Contactpage extends ContentItem {
    public heading!: Elements.TextElement;
    public formHeading!: Elements.TextElement;
    public emailLocale!: Elements.TextElement;
    public emailValue!: Elements.TextElement;
    public addressLocal!: Elements.TextElement;
    public addressValue!: Elements.TextElement;
    public socialLinksLocale!: Elements.TextElement;
    public firstName!: Elements.TextElement;
    public lastName!: Elements.TextElement;
    public phone!: Elements.TextElement;
    public yourEmail!: Elements.TextElement;
    public jobTitle!: Elements.TextElement;
    public company!: Elements.TextElement;
    public subject!: Elements.TextElement;
    public interestedIn!: Elements.TextElement;
    public nomination!: Elements.TextElement;
    public sponsor!: Elements.TextElement;
    public supportingPartner!: Elements.TextElement;
    public mediaPartner!: Elements.TextElement;
    public visitor!: Elements.TextElement;
    public message!: Elements.TextElement;
    public submit!: Elements.TextElement;
    public successMessage!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'form_heading') {
                    return 'formHeading';
                }
                if (elementName === 'email_locale') {
                    return 'emailLocale';
                }
                if (elementName === 'email_value') {
                    return 'emailValue';
                }
                if (elementName === 'address_local') {
                    return 'addressLocal';
                }
                if (elementName === 'address_value') {
                    return 'addressValue';
                }
                if (elementName === 'social_links_locale') {
                    return 'socialLinksLocale';
                }
                if (elementName === 'first_name') {
                    return 'firstName';
                }
                if (elementName === 'last_name') {
                    return 'lastName';
                }
                if (elementName === 'your_email') {
                    return 'yourEmail';
                }
                if (elementName === 'job_title') {
                    return 'jobTitle';
                }
                if (elementName === 'interested_in') {
                    return 'interestedIn';
                }
                if (elementName === 'supporting_partner') {
                    return 'supportingPartner';
                }
                if (elementName === 'media_partner') {
                    return 'mediaPartner';
                }
                if (elementName === 'success_message') {
                    return 'successMessage';
                }
                return elementName;
            })
        });
    }
}
