
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Aug 20 2025 13:53:33 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Globalcomponent extends ContentItem {
    public ecealogo!: Elements.AssetsElement;
    public selogo!: Elements.AssetsElement;
    public sewebsitelink!: Elements.TextElement;
    public patronagetext!: Elements.TextElement;
    public headermenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public footermenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public organizedbytext!: Elements.TextElement;
    public organizedbylogo!: Elements.AssetsElement;
    public organizedbywebsitelink!: Elements.TextElement;
    public copyrighttext!: Elements.TextElement;
    public facebookurl!: Elements.TextElement;
    public instagramurl!: Elements.TextElement;
    public xurl!: Elements.TextElement;
    public linkedinurl!: Elements.TextElement;
    public youtubeurl!: Elements.TextElement;
}
